/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenda;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class FrmAgenda extends javax.swing.JFrame {
    
    int linhaselecionada;

    /**
     * Creates new form FrmAgenda
     */
    public FrmAgenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxttelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtcelular = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtdata = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcmbsexo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jcmboperadora = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jbtnnovo = new javax.swing.JButton();
        jbtnatualizar = new javax.swing.JButton();
        jbtnexcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon("E:\\3 ano\\guto2\\icons8-calendário-48.png")); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(320, 0, 48, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 60);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados Pessoais"));
        jPanel2.setLayout(null);

        jLabel1.setText("Nome");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 30, 40, 14);
        jPanel2.add(jtxtnome);
        jtxtnome.setBounds(30, 50, 410, 20);

        jLabel2.setText("E-mail");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 80, 40, 14);
        jPanel2.add(jtxtemail);
        jtxtemail.setBounds(30, 100, 410, 20);

        jLabel3.setText("Telefone");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 130, 60, 14);
        jPanel2.add(jtxttelefone);
        jtxttelefone.setBounds(30, 150, 180, 20);

        jLabel4.setText("Celular");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(230, 130, 40, 14);
        jPanel2.add(jtxtcelular);
        jtxtcelular.setBounds(230, 150, 210, 20);

        jLabel5.setText("Data de Nascimento");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(490, 30, 110, 14);
        jPanel2.add(jtxtdata);
        jtxtdata.setBounds(490, 50, 190, 20);

        jLabel6.setText("Sexo");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(490, 80, 50, 14);

        jcmbsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino" }));
        jPanel2.add(jcmbsexo);
        jcmbsexo.setBounds(490, 100, 190, 20);

        jLabel7.setText("Operadora");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(490, 130, 70, 14);

        jcmboperadora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Tim ", "Claro", "Vivo", "Oi", "Nextel" }));
        jPanel2.add(jcmboperadora);
        jcmboperadora.setBounds(490, 150, 190, 20);

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data de Nascimento", "E-mail", "Sexo", "Telefone", "Celular", "Operadora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTabela);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(30, 180, 650, 100);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 70, 700, 300);

        jbtnnovo.setIcon(new javax.swing.ImageIcon("E:\\3 ano\\guto2\\icons8-adicionar-32.png")); // NOI18N
        jbtnnovo.setText("Novo");
        jbtnnovo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnovoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnnovo);
        jbtnnovo.setBounds(20, 380, 230, 30);

        jbtnatualizar.setIcon(new javax.swing.ImageIcon("E:\\3 ano\\guto2\\icons8-seta-para-recolher-32.png")); // NOI18N
        jbtnatualizar.setText("  Atualizar");
        jbtnatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnatualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnatualizar);
        jbtnatualizar.setBounds(260, 380, 230, 30);

        jbtnexcluir.setIcon(new javax.swing.ImageIcon("E:\\3 ano\\guto2\\icons8-cancelar-32.png")); // NOI18N
        jbtnexcluir.setText("Excluir");
        jbtnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnexcluir);
        jbtnexcluir.setBounds(500, 380, 210, 30);

        setSize(new java.awt.Dimension(739, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnovoActionPerformed
        // TODO add your handling code here:
        
        //Variáveis 
        String nome, email, sexo, telefone, celular, operadora, data;
        
        //Atribuir os valores das caixas para as varáveis
        nome = jtxtnome.getText();
        data = jtxtdata.getText();
        email = jtxtemail.getText();
        telefone = jtxttelefone.getText();
        celular = jtxtcelular.getText();
        data = jtxtdata.getText();
        sexo = jcmbsexo.getSelectedItem().toString();
        operadora = jcmboperadora.getSelectedItem().toString();
        
        //Adiciona uma nova linha na tabela 
        DefaultTableModel modelo = (DefaultTableModel) jTabela.getModel();
        modelo.addRow(new Object[]{nome, data, email, sexo, telefone, celular, operadora});
        
        //Limpar Campos 
        jtxtnome.setText("");
        jtxtemail.setText("");
        jtxttelefone.setText("");
        jtxtcelular.setText("");
        jtxtdata.setText("");
        jcmbsexo.setSelectedIndex(0);
        jcmboperadora.setSelectedIndex(0);
        
    }//GEN-LAST:event_jbtnnovoActionPerformed

    private void jbtnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexcluirActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTabela.getModel();
        //Se foi selecionada alguma linha do Jtabela
        if(jTabela.getSelectedRow()>=0){
            modelo.removeRow(jTabela.getSelectedRow());
        }
        else{
            JOptionPane.showMessageDialog(null, "Linha não selecionada");
        }                                  
    }//GEN-LAST:event_jbtnexcluirActionPerformed

    private void jTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMouseClicked
        // TODO add your handling code here:
        
        //Verifica se foi dado o duplo clique 
        if (evt.getClickCount() == 2){
            //Pega a linha selecionada 
            int linha = jTabela.getSelectedRow();
            //Adiciona os valores na caixa de texto
            jtxtnome.setText(jTabela.getValueAt(linha, 0).toString());
            jtxtdata.setText(jTabela.getValueAt(linha, 1).toString());
            jtxtemail.setText(jTabela.getValueAt(linha, 2).toString());
            jcmbsexo.setSelectedItem(jTabela.getValueAt(linha, 3).toString());
            jtxttelefone.setText(jTabela.getValueAt(linha, 4).toString());
            jtxtcelular.setText(jTabela.getValueAt(linha, 5).toString());
            jcmboperadora.setSelectedItem(jTabela.getValueAt(linha, 6).toString());
            
            //Armazena a linha selecionada 
            linhaselecionada = linha;
        }
        
    }//GEN-LAST:event_jTabelaMouseClicked

    private void jbtnatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnatualizarActionPerformed
        // TODO add your handling code here:
        
        String nome, email, sexo, telefone, celular, operadora, data;
        
        // atribui os valores das caixas de texto e combox para as respectivas
        //variaveis
        
        nome = jtxtnome.getText();
        email = jtxtemail.getText();
        telefone = jtxttelefone.getText();
        celular = jtxtcelular.getText();
        sexo = jcmbsexo.getSelectedItem().toString();
        data = jtxtdata.getText();
        operadora = jcmboperadora.getSelectedItem().toString();
        
        //alterta a linha no jtable
        DefaultTableModel modelo = (DefaultTableModel) jTabela.getModel();
        modelo.setValueAt(nome, linhaselecionada, 0);
        modelo.setValueAt(data, linhaselecionada, 1);
        modelo.setValueAt(email, linhaselecionada, 2);
        modelo.setValueAt(sexo, linhaselecionada, 3);
        modelo.setValueAt(telefone, linhaselecionada, 4);
        modelo.setValueAt(celular, linhaselecionada, 5);
        modelo.setValueAt(operadora, linhaselecionada, 6);
        
        
        
    }//GEN-LAST:event_jbtnatualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTabela;
    private javax.swing.JButton jbtnatualizar;
    private javax.swing.JButton jbtnexcluir;
    private javax.swing.JButton jbtnnovo;
    private javax.swing.JComboBox<String> jcmboperadora;
    private javax.swing.JComboBox<String> jcmbsexo;
    private javax.swing.JTextField jtxtcelular;
    private javax.swing.JTextField jtxtdata;
    private javax.swing.JTextField jtxtemail;
    private javax.swing.JTextField jtxtnome;
    private javax.swing.JTextField jtxttelefone;
    // End of variables declaration//GEN-END:variables
}
